@api = http://localhost:3000/api/tarefas

# Obter a lista de tarefas
GET {{api}}
Content-Type: application/json
###

# Inserir novo tarefas
POST {{api}}
Content-Type: application/json

{
 "resumo": "Iniciar o trabalho",
 "descricao": "asdiojiasjopjsakfasoh",
 "responsavel": "625f49cb8a4f190ad6c1713e",
 "categoria": "625f47a2e2cfa5c1954c1457"
}
###

# Alterar um tarefas
PUT {{api}}
Content-Type: application/json

{
 "_id": "625f4bbf7f6697ff9da57edf",
 "resumo": "Finalizar o trabalho",
 "descricao": "asdiojiasjopjsakfasoh",
 "status": 1,
 "responsavel": "625f49cb8a4f190ad6c1713e",
 "categoria": "625f47a2e2cfa5c1954c1457"
}
###

# Excluir um tarefas pelo id
DELETE {{api}}/625f4c687f6697ff9da57eeb
Content-Type: application/json
###

# Obter pelo id de tarefas
GET {{api}}/625f4c8110191630230eecff
Content-Type: application/json
###