@api = 'http://localhost:3000/api'

# Obter a lista de atividades
GET {{api}}/atividade
Content-Type: application/json
###

# Inserir novo atividade
POST {{api}}/atividade
Content-Type: application/json

{
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "status": "OK",
 "prazo": "2022-02-25T17:32:25.000Z",
 "agendaInicio": "2022-02-25T17:32:25.000Z",
 "colaborador": "6231332704433aa1d5eb0e78",
 "requisicao": "623a5fc26491048851c1b2f7"
}
###

# Alterar atividade
PUT {{api}}/atividade
Content-Type: application/json

{
 "_id": "623a660ced58e6368c0b0a92",
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "status": "OK",
 "prazo": "2022-02-25T17:32:25.000Z",
 "agendaInicio": "2022-02-25T17:32:25.000Z",
 "colaborador": "6231332704433aa1d5eb0e78",
 "requisicao": "623a5fc26491048851c1b2f7"
}
###
# Excluir um atividade
DELETE {{api}}/atividade/623a5f9b6491048851c1b2f0
Content-Type: application/json
###

# Obter pelo id de atividade
GET {{api}}/atividade/623a5fc26491048851c1b2f7
Content-Type: application/json
###

# Obter atividades filtrando
GET {{api}}/atividade/filtro/Nova
Content-Type: application/json
###