@api = http://localhost:3000/api/atividade
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlmZWYxYjgxMjNhOGFiM2FiZjlhYzciLCJub21lIjoiTHVjYXMiLCJpYXQiOjE2NTQ2NDk0MTIsImV4cCI6MzYwMDAxNjU0NjQ5NDEyfQ.DErliDeSxuHmsgq-07Nd7dWGLJ-QT34NE7GFjbSPql8

# Obter a lista de atividades
GET {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo atividade
POST {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "status": "OK",
 "prazo": "2022-02-25T17:32:25.000Z",
 "agendaInicio": "2022-02-25T17:32:25.000Z",
 "colaborador": "6231332704433aa1d5eb0e78",
 "requisicao": "623a5fc26491048851c1b2f7"
}
###

# Alterar atividade
PUT {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "623a660ced58e6368c0b0a92",
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "status": "OK",
 "prazo": "2022-02-25T17:32:25.000Z",
 "agendaInicio": "2022-02-25T17:32:25.000Z",
 "colaborador": "6231332704433aa1d5eb0e78",
 "requisicao": "623a5fc26491048851c1b2f7"
}
###
# Excluir um atividade
DELETE {{api}}/623a5f9b6491048851c1b2f0
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de atividade
GET {{api}}/623a5fc26491048851c1b2f7
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter atividades filtrando
GET {{api}}/filtro/Nova
Content-Type: application/json
x-auth-token: {{authToken}}
###