@api = 'http://localhost:3000/api'

# Obter a lista de colaboradores
GET {{api}}/colaborador
Content-Type: application/json
###

# Inserir novo colaborador
POST {{api}}/colaborador
Content-Type: application/json

{
 "nome": "Lucas", 
 "email": "lucas@upf.br",
 "senha": "lucas"
}
###

# Alterar colaborador
PUT {{api}}/colaborador
Content-Type: application/json

{
 "_id": "623a510c72b34b08b610e1fb",
 "nome": "Lucas alterado",
 "email": "teste@teste.com",
 "senha": "a1s2d3"
}
###
# Excluir um colaborador
DELETE {{api}}/colaborador/623a510c72b34b08b610e1fb
Content-Type: application/json
###

# Obter pelo id de colaborador
GET {{api}}/colaborador/6231332704433aa1d5eb0e78
Content-Type: application/json
###

# Obter colaboradores filtrando
GET {{api}}/colaborador/filtro/Ranielli
Content-Type: application/json
###