@api = http://localhost:3000/api/requisicao
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjlmZWYxYjgxMjNhOGFiM2FiZjlhYzciLCJub21lIjoiTHVjYXMiLCJpYXQiOjE2NTQ2NDk0MTIsImV4cCI6MzYwMDAxNjU0NjQ5NDEyfQ.DErliDeSxuHmsgq-07Nd7dWGLJ-QT34NE7GFjbSPql8

# Obter a lista de requisições
GET {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Inserir novo requisicao
POST {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "dataHoraCriada": "2022-01-25T17:32:25.000Z",
 "status": "OK",
 "prazoAtendimento": "2022-02-25T17:32:25.000Z",
 "tipoRequisicao": "623a5a86e632e1fefd8e730e",
 "solicitante": "623a57b75d2ec4064fac715e"
}
###


# Alterar requisicao
PUT {{api}}
Content-Type: application/json
x-auth-token: {{authToken}}

{
 "_id": "623a5f9b6491048851c1b2f0",
 "titulo": "Nova requisição", 
 "descricao": "requisição teste",
 "dataHoraCriada": "2022-01-25T17:32:25.000Z",
 "status": "OK",
 "prazoAtendimento": "2022-02-25T17:32:25.000Z",'
 "tipoRequisicao": "623a5a86e632e1fefd8e730e"
}
###
# Excluir um requisicao
DELETE {{api}}/623a57b75d2ec4064fac715e
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter pelo id de requisicao
GET {{api}}/623a5fc26491048851c1b2f7
Content-Type: application/json
x-auth-token: {{authToken}}
###

# Obter requisições filtrando
GET {{api}}/filtro/Nova
Content-Type: application/json
x-auth-token: {{authToken}}
###