@api = 'http://localhost:3000/api'

# Obter a lista de tipos de requisições
GET {{api}}/tipoRequisicao
Content-Type: application/json
###

# Inserir novo tipo de requisição
POST {{api}}/tipoRequisicao
Content-Type: application/json

{
 "descricao": "POST"
}
###

# Alterar requisição
PUT {{api}}/tipoRequisicao
Content-Type: application/json

{
 "_id": "623a5a56e632e1fefd8e7305",
 "descricao": "GET"
}
###
# Excluir um tipo de requisição
DELETE {{api}}/tipoRequisicao/623a5a56e632e1fefd8e7305
Content-Type: application/json
###

# Obter pelo id do tipo de requisição
GET {{api}}/tipoRequisicao/623a5a86e632e1fefd8e730e
Content-Type: application/json
###

# Obter requisições por filtro
GET {{api}}/tipoRequisicao/filtro/POST
Content-Type: application/json
###